version: '3.8'
services: 
  pg_database:
    image: postgres:13.3-alpine
    container_name: pg_database
    env_file: 
      - .env
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}  
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
