name: Nodejs CI
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          version: 14.x

      - name: Run install dependencies and running tests
        run: |
          npm install
          npm run test:ci

      - name: Coveralls
        uses: actions/setup-node@v1
        with:
          repo-token: ${{ github.token }}
          repository: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
